on: pull_request
name: Test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: "Restore golang bin cache"
      id: go-bin-cache
      uses: actions/cache@v2
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-go-bin-${{ hashFiles('~/go/bin') }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-bin-
    - name: "Restore golang mod cache"
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    - name: "Install dependencies"
      if: steps.go-bin-cache.outputs.cache-hit != 'true'
      run: make dependencies
      shell: bash
    - name: "Download latest app config"
      run: |
        make config
    - name: "Run go mod tidy"
      run: make tidy
    - name: "Run go fmt"
      run: make fmt
    - name: "Run go vet"
      run: make vet
      shell: bash
    - name: "Run revive"
      run: make revive
      shell: bash
    - name: "Static analysis check"
      run: make staticcheck
      shell: bash
    - name: "Security audit"
      run:  make gosec
      shell: bash
  test:
    strategy:
      matrix:
        tinygo-version: [0.24.0]
        go-version: [1.18.x]
        node-version: [12]
        rust-toolchain: [stable]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Install Go"
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: "Restore golang bin cache"
      uses: actions/cache@v2
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-go-bin-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-bin-
    - name: "Restore golang mod cache"
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    # NOTE: 
    # We can't install TinyGo for Windows without the scoop package manager. 
    # There is a third-party action that installs scoop but it's broken until its v2 is released.
    # https://github.com/MinoruSekine/setup-scoop/issues/7#issuecomment-1183050540
    - if: ${{ matrix.platform != 'windows-latest' }}
      id: tinygo
      run: echo ::set-output name=run_tests::true
    - if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v${{ matrix.tinygo-version }}/tinygo_${{ matrix.tinygo-version }}_amd64.deb
        sudo dpkg -i tinygo_${{ matrix.tinygo-version }}_amd64.deb
        echo "/usr/local/bin" >> $GITHUB_PATH
    - if: ${{ matrix.platform == 'macos-latest' }}
      run: |
        brew tap tinygo-org/tools
        brew install tinygo
        tinygo version
        # wget https://github.com/tinygo-org/tinygo/releases/download/v${{ matrix.tinygo-version }}/tinygo${{ matrix.tinygo-version }}.darwin-amd64.tar.gz
        # tar -xvf tinygo${{ matrix.tinygo-version }}.darwin-amd64.tar.gz
        # echo "${{ github.workspace }}/tinygo/bin" >> $GITHUB_PATH
    - name: "Install Rust"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: "Add wasm32-wasi Rust target"
      run: rustup target add wasm32-wasi --toolchain ${{ matrix.rust-toolchain }}
    - name: "Validate Rust toolchain"
      run: rustup show && rustup target list --installed --toolchain stable
      shell: bash
    - name: "Install Node"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Download latest app config"
      run: |
        make config
    - name: "Test suite"
      run: make test
      shell: bash
      env:
        TEST_COMPUTE_INIT: true
        TEST_COMPUTE_BUILD: true
        TEST_COMPUTE_DEPLOY: true
        TEST_COMPUTE_TINYGO: ${{ steps.tinygo.outputs.run_tests }}
